version: '3.8'

services:
  # Nó 1: Mestre / Coordenador
  node1:
    image: postgres:14
    container_name: node1
    hostname: node1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_db
    ports:
      # A LINHA ABAIXO FOI ALTERADA
      - "5431:5432" # MUDADO: Expõe o nó 1 na porta 5431 local (para evitar conflito)
    volumes:
      - node1_data:/var/lib/postgresql/data
    # Parâmetros de config do postgresql.conf
    command: >
      postgres
        -c wal_level=replica
        -c max_wal_senders=3
        -c archive_mode=on
        -c archive_command='test ! -f /tmp/%f && cp %p /tmp/%f'
        -c max_prepared_transactions=10

  # Nó 2: Escravo / Shard 1 / Participante 2PC
  node2:
    image: postgres:14
    container_name: node2
    hostname: node2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_db
    ports:
      - "5433:5432" # Expõe o nó 2 na porta 5433 local
    volumes:
      - node2_data:/var/lib/postgresql/data
    command: >
      postgres
        -c max_prepared_transactions=10

  # Nó 3: Shard 2 / Participante 2PC
  node3:
    image: postgres:14
    container_name: node3
    hostname: node3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_db
    ports:
      - "5434:5432" # Expõe o nó 3 na porta 5434 local
    volumes:
      - node3_data:/var/lib/postgresql/data
    command: >
      postgres
        -c max_prepared_transactions=10

# Volumes nomeados para persistir os dados
volumes:
  node1_data:
  node2_data:
  node3_data: